/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

/**
 *
 * @author ZOETEC
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        MenuCadastros = new javax.swing.JMenu();
        MenuCadHospedes = new javax.swing.JMenu();
        MenuCadHospe = new javax.swing.JMenuItem();
        MenuCadConsult = new javax.swing.JMenuItem();
        MenuCadQuartos = new javax.swing.JMenu();
        MenuQuartCad = new javax.swing.JMenuItem();
        MenuQuartConsult = new javax.swing.JMenuItem();
        MenuCadFuncio = new javax.swing.JMenu();
        MenuCadFuncio_cadastrar = new javax.swing.JMenuItem();
        MenuCadFuncio_consultar = new javax.swing.JMenuItem();
        MenuCadFornece = new javax.swing.JMenu();
        MenuCadForner_cadastrar = new javax.swing.JMenuItem();
        MenuCadFornecer_consultar = new javax.swing.JMenuItem();
        MenuCadProdut = new javax.swing.JMenu();
        MenuCadServico = new javax.swing.JMenu();
        MenuReservas = new javax.swing.JMenu();
        MenuReserva_Cadastrar = new javax.swing.JMenuItem();
        MenuResevar_consultar = new javax.swing.JMenuItem();
        MenuReseva_finalizar = new javax.swing.JMenuItem();
        MenuConsumo = new javax.swing.JMenu();
        MenuFinanceiro = new javax.swing.JMenu();
        MenuRelatorios = new javax.swing.JMenu();
        MenuSegurança = new javax.swing.JMenu();
        MenuFerramentas = new javax.swing.JMenu();
        MenuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        MenuCadastros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cadastro.png"))); // NOI18N
        MenuCadastros.setText("Cadastros   |");

        MenuCadHospedes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_hospede.png"))); // NOI18N
        MenuCadHospedes.setText("Hospedes");

        MenuCadHospe.setText("Cadastrar");
        MenuCadHospedes.add(MenuCadHospe);

        MenuCadConsult.setText("Consultar");
        MenuCadHospedes.add(MenuCadConsult);

        MenuCadastros.add(MenuCadHospedes);

        MenuCadQuartos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_quarto.png"))); // NOI18N
        MenuCadQuartos.setText("Quartos");

        MenuQuartCad.setText("Cadastrar");
        MenuCadQuartos.add(MenuQuartCad);

        MenuQuartConsult.setText("Consultar");
        MenuCadQuartos.add(MenuQuartConsult);

        MenuCadastros.add(MenuCadQuartos);

        MenuCadFuncio.setText("Funcionários");

        MenuCadFuncio_cadastrar.setText("Cadastrar");
        MenuCadFuncio.add(MenuCadFuncio_cadastrar);

        MenuCadFuncio_consultar.setText("Consultar");
        MenuCadFuncio.add(MenuCadFuncio_consultar);

        MenuCadastros.add(MenuCadFuncio);

        MenuCadFornece.setText("Fornecedores");

        MenuCadForner_cadastrar.setText("Cadastrar");
        MenuCadFornece.add(MenuCadForner_cadastrar);

        MenuCadFornecer_consultar.setText("Consultar");
        MenuCadFornece.add(MenuCadFornecer_consultar);

        MenuCadastros.add(MenuCadFornece);

        MenuCadProdut.setText("Produtos");
        MenuCadastros.add(MenuCadProdut);

        MenuCadServico.setText("Serviços");
        MenuCadastros.add(MenuCadServico);

        jMenuBar1.add(MenuCadastros);

        MenuReservas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/reservas.png"))); // NOI18N
        MenuReservas.setText("Reservas   |");

        MenuReserva_Cadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/3592829-calendar-general-month-month-calendar-office-schedule-wall-calendar_107756.png"))); // NOI18N
        MenuReserva_Cadastrar.setText("Cadastrar Reserva");
        MenuReservas.add(MenuReserva_Cadastrar);

        MenuResevar_consultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/3592851-calendar-general-month-month-calendar-office-schedule-wall-calendar_107740.png"))); // NOI18N
        MenuResevar_consultar.setText("Consultar Reserva");
        MenuReservas.add(MenuResevar_consultar);

        MenuReseva_finalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/3592863-accounting-calculate-calculation-calculator-general-math-office_107744.png"))); // NOI18N
        MenuReseva_finalizar.setText("Finalizar Reserva");
        MenuReservas.add(MenuReseva_finalizar);

        jMenuBar1.add(MenuReservas);

        MenuConsumo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/consumo.png"))); // NOI18N
        MenuConsumo.setText("Consumo   |");
        jMenuBar1.add(MenuConsumo);

        MenuFinanceiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/financeiro.png"))); // NOI18N
        MenuFinanceiro.setText("Financeiro   |");
        jMenuBar1.add(MenuFinanceiro);

        MenuRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/business_salesreport_salesreport_negocio_2353.png"))); // NOI18N
        MenuRelatorios.setText("Relatórios   |");
        jMenuBar1.add(MenuRelatorios);

        MenuSegurança.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/seguranca.png"))); // NOI18N
        MenuSegurança.setText("Segurança   |");
        jMenuBar1.add(MenuSegurança);

        MenuFerramentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ferramentas.png"))); // NOI18N
        MenuFerramentas.setText("Ferramentas    |");
        jMenuBar1.add(MenuFerramentas);

        MenuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sair.png"))); // NOI18N
        MenuSair.setText("Sair");
        jMenuBar1.add(MenuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 679, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuCadConsult;
    private javax.swing.JMenu MenuCadFornece;
    private javax.swing.JMenuItem MenuCadFornecer_consultar;
    private javax.swing.JMenuItem MenuCadForner_cadastrar;
    private javax.swing.JMenu MenuCadFuncio;
    private javax.swing.JMenuItem MenuCadFuncio_cadastrar;
    private javax.swing.JMenuItem MenuCadFuncio_consultar;
    private javax.swing.JMenuItem MenuCadHospe;
    private javax.swing.JMenu MenuCadHospedes;
    private javax.swing.JMenu MenuCadProdut;
    private javax.swing.JMenu MenuCadQuartos;
    private javax.swing.JMenu MenuCadServico;
    private javax.swing.JMenu MenuCadastros;
    private javax.swing.JMenu MenuConsumo;
    private javax.swing.JMenu MenuFerramentas;
    private javax.swing.JMenu MenuFinanceiro;
    private javax.swing.JMenuItem MenuQuartCad;
    private javax.swing.JMenuItem MenuQuartConsult;
    private javax.swing.JMenu MenuRelatorios;
    private javax.swing.JMenuItem MenuReserva_Cadastrar;
    private javax.swing.JMenu MenuReservas;
    private javax.swing.JMenuItem MenuReseva_finalizar;
    private javax.swing.JMenuItem MenuResevar_consultar;
    private javax.swing.JMenu MenuSair;
    private javax.swing.JMenu MenuSegurança;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
